name: EC2 Node js Deployment

on:
  push:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v4
        - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          export PATH=$PATH:/home/ubuntu/.nvm/versions/node/$(node -v)/bin
          cd /home/ubuntu/cicd_ec2_demo
          git pull origin main
          npm install
          pm2 restart all || pm2 start index.js --name "cicd_ec2_demo"
