name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Navigate to repo (ensure this folder exists!)
            cd /home/ubuntu/cicd_ec2_demo || exit
            
            # Update code
            git pull origin main
            
            # Load Node and NPM
            export PATH=$PATH:/usr/bin:/usr/local/bin
            npm install --production
            
            # Restart App
            pm2 restart cicd_ec2_demo || pm2 start index.js --name "cicd_ec2_demo"